### ISSUE TITLE
Issues in vercel deployment 

### ISSUE THREAD

**Issue by hpymntn** [oleeskild/digitalgarden#62]
Vercel deployment failed with the following errors

```
Running build in San Francisco, USA (West) – sfo1
--
11:19:43.750 | Cloning github.com/hpymntn/digitalgarden (Branch: main, Commit: 723bd84)
11:19:43.888 | Previous build cache not available
11:19:44.720 | Cloning completed: 969.411ms
11:19:44.813 | Running "vercel build"
11:19:45.216 | Vercel CLI 28.14.1
11:19:46.153 | Running "install" command: `npm install`...
11:19:49.440 | npm WARN deprecated har-validator@5.1.5: this library is no longer supported
11:19:49.465 | npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
11:19:49.739 | npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
11:19:50.500 | npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
11:19:53.999 |  
11:19:53.999 | added 624 packages, and audited 625 packages in 8s
11:19:53.999 |  
11:19:53.999 | 80 packages are looking for funding
11:19:53.999 | run `npm fund` for details
11:19:54.009 |  
11:19:54.009 | 14 vulnerabilities (3 moderate, 10 high, 1 critical)
11:19:54.009 |  
11:19:54.009 | To address issues that do not require attention, run:
11:19:54.009 | npm audit fix
11:19:54.009 |  
11:19:54.009 | Some issues need review, and may require choosing
11:19:54.009 | a different dependency.
11:19:54.010 |  
11:19:54.277 |  
11:19:54.277 | > web@1.0.0 build
11:19:54.277 | > npm-run-all get-theme build:*
11:19:54.277 |  
11:19:54.633 |  
11:19:54.634 | > web@1.0.0 get-theme
11:19:54.634 | > node src/site/get-theme.js
11:19:54.634 |  
11:19:54.972 |  
11:19:54.972 | > web@1.0.0 build:eleventy
11:19:54.972 | > cross-env ELEVENTY_ENV=prod NODE_OPTIONS=--max-old-space-size=4096 eleventy
11:19:54.972 |  
11:19:55.618 | [11ty] Problem writing Eleventy templates: (more in DEBUG output)
11:19:55.618 | [11ty] Cannot read properties of undefined (reading 'forEach') (via TypeError)
11:19:55.618 | [11ty]
11:19:55.619 | [11ty] Original error stack trace: TypeError: Cannot read properties of undefined (reading 'forEach')
11:19:55.619 | [11ty]     at getGraph (/vercel/path0/src/helpers/linkUtils.js:38:25)
11:19:55.619 | [11ty]     at Object.graph (/vercel/path0/src/site/_data/eleventyComputed.js:4:22)
11:19:55.619 | [11ty]     at ComputedData._setupDataEntry (/vercel/path0/node_modules/@11ty/eleventy/src/ComputedData.js:97:25)
11:19:55.619 | [11ty]     at ComputedData.processRemainingData (/vercel/path0/node_modules/@11ty/eleventy/src/ComputedData.js:118:16)
11:19:55.619 | [11ty]     at Template.resolveRemainingComputedData (/vercel/path0/node_modules/@11ty/eleventy/src/Template.js:674:29)
11:19:55.619 | [11ty]     at TemplateMap.resolveRemainingComputedData (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateMap.js:619:37)
11:19:55.620 | [11ty]     at TemplateMap.cache (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateMap.js:346:16)
11:19:55.620 | [11ty]     at async TemplateWriter.generateTemplates (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateWriter.js:277:5)
11:19:55.620 | [11ty]     at async TemplateWriter.write (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateWriter.js:323:23)
11:19:55.620 | [11ty] Wrote 0 files in 0.10 seconds (v1.0.2)
11:19:55.636 | ERROR: "build:eleventy" exited with 1.
11:19:55.653 | Error: Command "npm run build" exited with 1


```

**Comment by oleeskild** [comment]
Thanks for letting me know @hpymntn ! The issue seems to happen when no notes has been added. Publishing a note should fix it. But I've also released a fix for the template that should fix the issue, so that new gardens with now notes will work when building. You can [update the template](https://dg-docs.ole.dev/getting-started/06-updating-the-template/) to get the fix.
