### ISSUE TITLE
I don't push the file ? why?

### ISSUE THREAD

**Issue by liangfeng093** [oleeskild/digitalgarden#79]
10:32:50 AM:   1. build.command from netlify.toml                            
10:32:50 AM: ────────────────────────────────────────────────────────────────
10:32:50 AM: ​
10:32:50 AM: $ npm install && npm run build
10:32:51 AM: up to date, audited 511 packages in 657ms
10:32:51 AM: 85 packages are looking for funding
10:32:51 AM:   run `npm fund` for details
10:32:51 AM: 8 vulnerabilities (1 moderate, 6 high, 1 critical)
10:32:51 AM: Some issues need review, and may require choosing
10:32:51 AM: a different dependency.
10:32:51 AM: Run `npm audit` for details.
10:32:52 AM: > web@1.0.0 build
10:32:52 AM: > npm-run-all get-theme build:*
10:32:52 AM: > web@1.0.0 get-theme
10:32:52 AM: > node src/site/get-theme.js
10:32:52 AM: > web@1.0.0 build:eleventy
10:32:52 AM: > cross-env ELEVENTY_ENV=prod NODE_OPTIONS=--max-old-space-size=4096 eleventy
10:32:53 AM: [11ty] Problem writing Eleventy templates: (more in DEBUG output)
10:32:53 AM: [11ty] Output conflict: multiple input files are writing to `dist/index.html`. Use distinct `permalink` values to resolve this conflict.
10:32:53 AM: [11ty]   1. ./src/site/notes/对象之间的关系.md
10:32:53 AM: [11ty]   2. ./src/site/index.njk (via DuplicatePermalinkOutputError)
10:32:53 AM: [11ty]
10:32:53 AM: [11ty] Original error stack trace: (Repeated output has been truncated…)
10:32:53 AM: [11ty]     at TemplateMap.checkForDuplicatePermalinks (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateMap.js:799:13)
10:32:53 AM: [11ty]     at TemplateMap.cache (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateMap.js:484:10)
10:32:53 AM: [11ty]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
10:32:53 AM: [11ty]     at async TemplateWriter._createTemplateMap (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateWriter.js:330:5)
10:32:53 AM: [11ty]     at async TemplateWriter.generateTemplates (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateWriter.js:360:5)
10:32:53 AM: [11ty]     at async TemplateWriter.write (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateWriter.js:407:23)
10:32:53 AM: [11ty]     at async Eleventy.executeBuild (/opt/build/repo/node_modules/@11ty/eleventy/src/Eleventy.js:1160:13)
10:32:53 AM: [11ty] Copied 7 files / Wrote 0 files in 0.32 seconds (v2.0.0)
10:32:53 AM: ERROR: "build:eleventy" exited with 1.
10:32:53 AM: ​
10:32:54 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
10:32:53 AM:   "build.command" failed                                        
10:32:53 AM: ────────────────────────────────────────────────────────────────
10:32:53 AM: ​
10:32:53 AM:   Error message
10:32:53 AM:   Command failed with exit code 1: npm install && npm run build (https://ntl.fyi/exit-code-1)
10:32:53 AM: ​
10:32:53 AM:   Error location
10:32:53 AM:   In build.command from netlify.toml:
10:32:53 AM:   npm install && npm run build
10:32:53 AM: ​
10:32:53 AM:   Resolved config
10:32:53 AM:   build:
10:32:53 AM:     command: npm install && npm run build
10:32:53 AM:     commandOrigin: config
10:32:53 AM:     publish: /opt/build/repo/dist
10:32:53 AM:     publishOrigin: config
10:32:53 AM:   functionsDirectory: /opt/build/repo/netlify/functions
10:32:53 AM:   redirects:
10:32:54 AM:     - from: /api/*
      status: 200
      to: /.netlify/functions/:splat
    - from: /*
      status: 404
      to: /404
  redirectsOrigin: config
Caching artifacts

**Comment by oleeskild** [comment]
I think this has to do with your note titles using non-English characters. Try turning off "Slugify note URL" in the plugin setting, and republish everyting and see if that helps.
